
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  environment:
    name: Dev


test-job1:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "deply stage"
    - cp -rf ./ /root/front
    - cd /root/front
    - npm run build
